name: linux-dwarf-pack
base: core18
version: 0.47.05-rc3
summary: Dwarf Fortress
description: A simple ready-to-play Dwarf Fortress starter pack
grade: stable
confinement: devmode
apps:
  linux-dwarf-pack:
    command: /opt/linux-dwarf-pack/linux-dwarf-pack.sh
parts:
  linux-dwarf-pack:
    build-packages: [libxml-libxml-perl, libxml-xslt-perl, libxml-filter-xslt-perl, mercurial, help2man, git, openjdk-8-jre, libncurses5-dev, zlib1g-dev, lib32z1-dev, mesa-common-dev, gcc-multilib, g++-multilib, cmake, dos2unix, tcl, autoconf, gperf, bison, flex, gawk, libtool, libsdl-dev, libsdl-image1.2, libsdl-ttf2.0-0, texinfo, ninja-build, qt5-qmake, qttools5-dev-tools, qt5-default, libqt5svg5-dev, qt5-image-formats-plugins, qtbase5-dev, qtdeclarative5-dev, python3-tk, libasound2-dev, libgtk-3-dev, libwebkit2gtk-4.0-dev, cargo, wget, rsync]
    stage-packages: [libsdl-image1.2, libsdl-ttf2.0-0, libopenal1, libsndfile1, gnome-terminal, openjdk-11-jre, python3-tk, python3-distutils, python3-pil.imagetk, libqt5qml5, libqt5concurrent5, libqt5gui5, unionfs-fuse, libcanberra-gtk-module]
    plugin: autotools
    source: .
    override-build: |
      echo CT_LOG_PROGRESS_BAR=n >> .config
      echo CT_ALLOW_BUILD_AS_ROOT_SURE=y >> .config
      autoconf
      ./configure --prefix=/home/runner/work/lnp-forge/lnp-forge
      make install
      LD_LIBRARY_PATH= LIBRARY_PATH= LPATH= CFLAGS= CXXFLAGS= GREP_OPTIONS= bin/lnp-forge build
      mkdir -p /opt/linux-dwarf-pack
      rsync -qa ".build/src/lnp-0.14a/*" /opt/linux-dwarf-pack
architectures:
  - build-on: amd64
contact: http://www.bay12forums.com/smf/index.php?topic=157712
website: http://www.bay12forums.com/smf/index.php?topic=157712
source-code: https://github.com/McArcady/lnp-forge
donation: https://www.paypal.com/donate/?business=mcarcady%40gmail.com&item_name=Create+and+expand+the+LinuxDwarfPack%21&currency_code=EUR
#icon: /usr/share/icons/hicolor/256x256/apps/linux-dwarf-pack.png
license: Proprietary
